#ifndef STATE_MACHINE_H_INCLUDED
#define STATE_MACHINE_H_INCLUDED

// STATE_TAKE_OVER needs to be the last one
typedef enum {STATE_IDLE, STATE_FIND_TRACK, STATE_FOLLOW_TRACK_1, STATE_Y_INTERSECTION, STATE_FOLLOW_TRACK_2, STATE_TAKE_OVER, STATE_ANY} state_t;
// has to be in the same order as in java
typedef enum {JAVA_IDLE,  JAVA_FIND_TRACK,  JAVA_FOLLOW_TRACK_1,  JAVA_Y_INTERSECTION,  JAVA_FOLLOW_TRACK_2, EVENT_BUTTON_START, EVENT_BUTTON_RESET, EVENT_LINE_FOUND, EVENT_ALL_SENSORS_BLACK} event_t;

extern state_t state;

void state_machine();

#endif // STATE_MACHINE_H_INCLUDED
